### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by alebianco** [williamjacksn/birthdayfeed#225]
first of all, thanks for this! been using it for a while and it's awesome

I encountered a small issue while trying to make my calendar a bit more fun.
The CSV exported from google sheets looks like this
```csv
🎂 Person 1,1955,01,01
🐱 Pet 1,2014,01,01
🎂 Person 2,1988,01,01
```
to diversify people, pets and various kinds of anniversaries

What I get back in calendar is something like
```
馃惐 Pet 1 turns 10
January, 01 April
馃惐 Pet 1, born January 01, 2014, will turn 10 on Thursday, 
```

I looked around in various settings of sheets and calendar but I haven't found a way there to tweak the character encoding to fix the issue

**Comment by williamjacksn** [comment]
Are you using Google Calendar?

**Comment by williamjacksn** [comment]
For reference, here is an example with the ⚡ emoji in a name:

![image](https://github.com/williamjacksn/birthdayfeed/assets/565174/746a9531-0aaa-4e1f-aef8-947c21a58f4e)

**Comment by alebianco** [comment]
yes, google sheets and google calendar
do you think there is some setting somewhere that I might have missed?

**Comment by williamjacksn** [comment]
I am not aware of any settings in Google Sheets or Calendar that would affect this, but I assume from your profile that you are using an Italian locale with these products. Still, these emoji should be encoded the same way regardless.

Would you be willing to create a sample spreadsheet with just one entry that exhibits this behavior and share it with me?

**Comment by alebianco** [comment]
I made a copy of the problematic sheet ( https://docs.google.com/spreadsheets/d/1-giw6xf2iQYdr1P4UOaS2pnMiyk3UtVlG8mj_w1UPXY/edit?usp=sharing ) with some mock and was very confused when I tested it and the emoji worked fine, then I read your last comment :D

with the forced encoding even the data from original sheet now is showing up as expected, thanks! <3
