### ISSUE TITLE
Updating calendars

### ISSUE THREAD

**Issue by revcomninos** [williamjacksn/birthdayfeed#47]
I created a birthday and anniversary calendar in Google sheets. I have noticed though that updating the CSV file with new data does not automatically update the calendar.

**Comment by williamjacksn** [comment]
Is this with Google Calendar? Do you have more than about 25 names in your list? You may be hitting a size limit with Google Calendar. If this is the case, you will need to have multiple lists and subscribe to each of them individually.

**Comment by revcomninos** [comment]
Thanks for responding. No, the lists are short, with no more than 6 entries.

**Comment by williamjacksn** [comment]
I have not seen any errors in the server logs recently, so I believe the files are being generated correctly. How much time has passed since you added the new data to the list? I don't know how often Google Calendar checks for new data.

**Comment by revcomninos** [comment]
That's a good point. I will check again tomorrow and revert. Thank you.

**Comment by revcomninos** [comment]
Thank you. It is working! It seems Google updates once a day.
